// <auto-generated />
// ReSharper disable InconsistentNaming

#pragma warning disable 0169 

using System;

namespace Microsoft.Data.Entity.Utilities
{
	internal partial class RelationalImplyTypes
	{
		// value types
		RelationalImplyGeneric<char> Prop101;
		RelationalImplyGeneric<char?> Prop102;
		RelationalImplyGeneric<short> Prop103;
		RelationalImplyGeneric<short?> Prop104;
		RelationalImplyGeneric<ushort> Prop105;
		RelationalImplyGeneric<ushort?> Prop106;
		RelationalImplyGeneric<int> Prop107;
		RelationalImplyGeneric<int?> Prop108;
		RelationalImplyGeneric<uint> Prop109;
		RelationalImplyGeneric<uint?> Prop110;
		RelationalImplyGeneric<long> Prop111;
		RelationalImplyGeneric<long?> Prop112;
		RelationalImplyGeneric<ulong> Prop113;
		RelationalImplyGeneric<ulong?> Prop114;
		RelationalImplyGeneric<double> Prop115;
		RelationalImplyGeneric<double?> Prop116;
		RelationalImplyGeneric<decimal> Prop117;
		RelationalImplyGeneric<decimal?> Prop118;
		RelationalImplyGeneric<float> Prop119;
		RelationalImplyGeneric<float?> Prop120;
		RelationalImplyGeneric<bool> Prop121;
		RelationalImplyGeneric<bool?> Prop122;
		RelationalImplyGeneric<byte> Prop123;
		RelationalImplyGeneric<byte?> Prop124;
		RelationalImplyGeneric<Guid> Prop125;
		RelationalImplyGeneric<Guid?> Prop126;
		RelationalImplyGeneric<TimeSpan> Prop127;
		RelationalImplyGeneric<TimeSpan?> Prop128;
		RelationalImplyGeneric<DateTime> Prop129;
		RelationalImplyGeneric<DateTime?> Prop130;
		RelationalImplyGeneric<DateTimeOffset> Prop131;
		RelationalImplyGeneric<DateTimeOffset?> Prop132;
	}

	internal partial class RelationalImplyGeneric<T>
	{
		// system objects
        RelationalImplyGeneric<object, T> Prop133;
        RelationalImplyGeneric<T, object> Prop134;
        RelationalImplyGeneric<string, T> Prop135;
        RelationalImplyGeneric<T, string> Prop136;

		RelationalImplyGeneric<char, T> Prop137;
		RelationalImplyGeneric<char?, T> Prop138;
		RelationalImplyGeneric<T, char> Prop139;
		RelationalImplyGeneric<T, char?> Prop140;
		RelationalImplyGeneric<short, T> Prop141;
		RelationalImplyGeneric<short?, T> Prop142;
		RelationalImplyGeneric<T, short> Prop143;
		RelationalImplyGeneric<T, short?> Prop144;
		RelationalImplyGeneric<ushort, T> Prop145;
		RelationalImplyGeneric<ushort?, T> Prop146;
		RelationalImplyGeneric<T, ushort> Prop147;
		RelationalImplyGeneric<T, ushort?> Prop148;
		RelationalImplyGeneric<int, T> Prop149;
		RelationalImplyGeneric<int?, T> Prop150;
		RelationalImplyGeneric<T, int> Prop151;
		RelationalImplyGeneric<T, int?> Prop152;
		RelationalImplyGeneric<uint, T> Prop153;
		RelationalImplyGeneric<uint?, T> Prop154;
		RelationalImplyGeneric<T, uint> Prop155;
		RelationalImplyGeneric<T, uint?> Prop156;
		RelationalImplyGeneric<long, T> Prop157;
		RelationalImplyGeneric<long?, T> Prop158;
		RelationalImplyGeneric<T, long> Prop159;
		RelationalImplyGeneric<T, long?> Prop160;
		RelationalImplyGeneric<ulong, T> Prop161;
		RelationalImplyGeneric<ulong?, T> Prop162;
		RelationalImplyGeneric<T, ulong> Prop163;
		RelationalImplyGeneric<T, ulong?> Prop164;
		RelationalImplyGeneric<double, T> Prop165;
		RelationalImplyGeneric<double?, T> Prop166;
		RelationalImplyGeneric<T, double> Prop167;
		RelationalImplyGeneric<T, double?> Prop168;
		RelationalImplyGeneric<decimal, T> Prop169;
		RelationalImplyGeneric<decimal?, T> Prop170;
		RelationalImplyGeneric<T, decimal> Prop171;
		RelationalImplyGeneric<T, decimal?> Prop172;
		RelationalImplyGeneric<float, T> Prop173;
		RelationalImplyGeneric<float?, T> Prop174;
		RelationalImplyGeneric<T, float> Prop175;
		RelationalImplyGeneric<T, float?> Prop176;
		RelationalImplyGeneric<bool, T> Prop177;
		RelationalImplyGeneric<bool?, T> Prop178;
		RelationalImplyGeneric<T, bool> Prop179;
		RelationalImplyGeneric<T, bool?> Prop180;
		RelationalImplyGeneric<byte, T> Prop181;
		RelationalImplyGeneric<byte?, T> Prop182;
		RelationalImplyGeneric<T, byte> Prop183;
		RelationalImplyGeneric<T, byte?> Prop184;
		RelationalImplyGeneric<Guid, T> Prop185;
		RelationalImplyGeneric<Guid?, T> Prop186;
		RelationalImplyGeneric<T, Guid> Prop187;
		RelationalImplyGeneric<T, Guid?> Prop188;
		RelationalImplyGeneric<TimeSpan, T> Prop189;
		RelationalImplyGeneric<TimeSpan?, T> Prop190;
		RelationalImplyGeneric<T, TimeSpan> Prop191;
		RelationalImplyGeneric<T, TimeSpan?> Prop192;
		RelationalImplyGeneric<DateTime, T> Prop193;
		RelationalImplyGeneric<DateTime?, T> Prop194;
		RelationalImplyGeneric<T, DateTime> Prop195;
		RelationalImplyGeneric<T, DateTime?> Prop196;
		RelationalImplyGeneric<DateTimeOffset, T> Prop197;
		RelationalImplyGeneric<DateTimeOffset?, T> Prop198;
		RelationalImplyGeneric<T, DateTimeOffset> Prop199;
		RelationalImplyGeneric<T, DateTimeOffset?> Prop200;
	}
}
